# Generated by Django 4.2.7 on 2023-11-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_buyer_cart_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="orders",
            field=models.ManyToManyField(
                blank=True, related_name="buyers", to="api.order"
            ),
        ),
    ]
