# Generated by Django 4.2.7 on 2023-11-16 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0010_remove_product_image_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="address",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_address",
                to="api.delivery_address",
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="cart",
            field=models.OneToOneField(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="api.cart"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="history",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.history",
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="orders",
            field=models.ManyToManyField(
                default=None, related_name="buyers", to="api.order"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="transaction",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
