# Generated by Django 4.2.7 on 2023-11-16 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_buyer_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="address",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_address",
                to="api.delivery_address",
            ),
        ),
    ]
